output_dir: outputs/training/3dgs_res_704_1280_views_121_multi_6_dynamic_prune
data_mode: [['lyra_dynamic', 1]]
img_size: [704, 1280]
num_views: 133
num_input_views: 121
gs_view_chunk_size: 1
num_input_multi_views: 6
batch_size: 1
static_view_indices_sampling: random_bucket
static_frame_sampling: exponential
lpips_chunk_size: 1
lambda_opacity: 0.1
gaussians_prune_ratio: 0.8
gaussians_random_ratio: 0.0
# use flipped supervision
select_target_views_input_dynamic: false
use_time_embedding: true
checkpointing_steps: 2
max_train_steps: 2